"""Text preprocessing helpers for the standalone modular project."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

from backend.config import PROCESSED_DATA_DIR, REPORTS_DIR, ensure_project_dirs


URL_PATTERN = re.compile(r"https?://\S+|www\.\S+", flags=re.IGNORECASE)
MULTISPACE_PATTERN = re.compile(r"\s+")
TOKEN_PATTERN = re.compile(r"[a-z]+")

# Conservative typo corrections to avoid over-editing domain-specific language.
TYPO_CORRECTIONS = {
    "covvi": "covid",
    "wating": "waiting",
    "recieve": "receive",
    "insurrance": "insurance",
    "insurrer": "insurer",
    "cancelation": "cancellation",
    "definately": "definitely",
}

STOPWORDS = set(ENGLISH_STOP_WORDS)


@dataclass
class PreprocessingArtifacts:
    """Container for outputs generated by preprocessing."""

    clean_df: pd.DataFrame
    report: dict[str, Any]


def _safe_text(value: Any) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    text = str(value).strip()
    if text.lower() in {"nan", "none", "null"}:
        return ""
    return text


def _clean_basic_text(text: str) -> str:
    text = _safe_text(text)
    text = text.replace("\r", " ").replace("\n", " ").strip()
    text = URL_PATTERN.sub(" ", text)
    text = MULTISPACE_PATTERN.sub(" ", text)
    return text.strip()


def _apply_typo_corrections(text: str, corrections: dict[str, str]) -> str:
    corrected = text
    for src, dst in corrections.items():
        corrected = re.sub(rf"\b{re.escape(src)}\b", dst, corrected, flags=re.IGNORECASE)
    return corrected


def _text_for_classical_ml(text: str) -> str:
    text = text.lower()
    tokens = TOKEN_PATTERN.findall(text)
    tokens = [tok for tok in tokens if tok not in STOPWORDS and len(tok) >= 2]
    return " ".join(tokens)


def _choose_primary_text(row: pd.Series) -> tuple[str, str]:
    avis_en = _safe_text(row.get("text_translated_en", "")).strip()
    avis_fr = _safe_text(row.get("text_raw_fr", "")).strip()
    if avis_en:
        return avis_en, "en_translated"
    return avis_fr, "fr_fallback"


def _derive_sentiment_from_note(note: Any) -> str | None:
    if pd.isna(note):
        return None
    note_value = float(note)
    if note_value <= 2.0:
        return "negative"
    if note_value == 3.0:
        return "neutral"
    return "positive"


def prepare_text_record(text: str) -> dict[str, str]:
    """Prepare one free-text review for prediction or search."""
    text_raw = _safe_text(text)
    text_clean_basic = _clean_basic_text(text_raw)
    text_clean_corrected = _apply_typo_corrections(text_clean_basic, TYPO_CORRECTIONS)
    text_clean_corrected = MULTISPACE_PATTERN.sub(" ", text_clean_corrected).strip()
    text_for_classical_ml = _text_for_classical_ml(text_clean_corrected)
    text_for_deep_learning = text_clean_corrected.lower()
    return {
        "text_raw": text_raw,
        "text_clean_basic": text_clean_basic,
        "text_clean_corrected": text_clean_corrected,
        "text_for_classical_ml": text_for_classical_ml,
        "text_for_deep_learning": text_for_deep_learning,
    }


def build_clean_dataset(raw_df: pd.DataFrame) -> PreprocessingArtifacts:
    """Create cleaned columns and duplicate flags from merged raw reviews."""
    df = raw_df.copy()

    initial_rows = len(df)
    dedup_subset = [col for col in df.columns if col != "row_id"]
    exact_dups = int(df.duplicated(subset=dedup_subset).sum())
    df["is_exact_duplicate"] = df.duplicated(subset=dedup_subset, keep="first").astype(int)

    df["auteur"] = df["auteur"].fillna("unknown_author")
    df["assureur"] = df["assureur"].fillna("unknown_assureur")
    df["produit"] = df["produit"].fillna("unknown_product")

    df["text_raw_fr"] = df["avis"].map(_safe_text)
    df["text_translated_en"] = df["avis_en"].map(_safe_text)

    df["date_publication"] = pd.to_datetime(df["date_publication"], errors="coerce", dayfirst=True)
    df["date_exp"] = pd.to_datetime(df["date_exp"], errors="coerce", dayfirst=True)
    df["publication_year"] = df["date_publication"].dt.year
    df["extraction_year"] = df["date_exp"].dt.year

    chosen = df.apply(_choose_primary_text, axis=1, result_type="expand")
    df["text_raw"] = chosen[0]
    df["text_source"] = chosen[1]

    df["text_clean_basic"] = df["text_raw"].map(_clean_basic_text)

    manual_corrected = df["avis_cor_en"].map(_safe_text)
    has_manual_corrected_text = manual_corrected.ne("")
    corrected_auto = df["text_clean_basic"].map(lambda x: _apply_typo_corrections(x, TYPO_CORRECTIONS))
    corrected_auto = corrected_auto.map(lambda x: MULTISPACE_PATTERN.sub(" ", x).strip())
    df["text_clean_corrected"] = corrected_auto
    df.loc[has_manual_corrected_text, "text_clean_corrected"] = manual_corrected[has_manual_corrected_text]
    df["has_manual_correction"] = has_manual_corrected_text.astype(int)

    df["text_for_classical_ml"] = df["text_clean_corrected"].map(_text_for_classical_ml)
    df["text_for_deep_learning"] = df["text_clean_corrected"].str.lower().map(_clean_basic_text)

    df["text_char_len"] = df["text_clean_corrected"].str.len()
    df["text_word_len"] = df["text_clean_corrected"].str.split().str.len()
    df["sentiment_label"] = df["note"].map(_derive_sentiment_from_note)

    normalized_key = (
        df["text_clean_basic"]
        .str.lower()
        .str.replace(MULTISPACE_PATTERN, " ", regex=True)
        .str.strip()
    )
    df["is_text_duplicate_global"] = normalized_key.duplicated(keep="first").astype(int)
    df["is_text_duplicate_within_split"] = (
        df.assign(_text_key=normalized_key)
        .duplicated(subset=["type", "_text_key"], keep="first")
        .astype(int)
    )

    train_mask = df["type"].eq("train")
    df["is_text_duplicate_train"] = 0
    df.loc[train_mask, "is_text_duplicate_train"] = normalized_key[train_mask].duplicated(keep="first").astype(int)

    report: dict[str, Any] = {
        "initial_rows": initial_rows,
        "rows_retained_in_clean_file": int(len(df)),
        "rows_after_exact_dedup_if_applied": int(initial_rows - exact_dups),
        "exact_duplicates_flagged": exact_dups,
        "train_rows": int(df["type"].eq("train").sum()),
        "test_rows": int(df["type"].eq("test").sum()),
        "missing_note_count": int(df["note"].isna().sum()),
        "manual_correction_rows": int(df["has_manual_correction"].sum()),
        "global_text_duplicates": int(df["is_text_duplicate_global"].sum()),
        "train_text_duplicates": int(df.loc[train_mask, "is_text_duplicate_train"].sum()),
        "text_source_distribution": df["text_source"].value_counts(dropna=False).to_dict(),
    }
    return PreprocessingArtifacts(clean_df=df, report=report)


def save_preprocessing_outputs(
    artifacts: PreprocessingArtifacts,
    output_csv_path: Path,
    output_report_path: Path,
) -> None:
    """Persist cleaned dataset and preprocessing report."""
    output_csv_path.parent.mkdir(parents=True, exist_ok=True)
    output_report_path.parent.mkdir(parents=True, exist_ok=True)
    artifacts.clean_df.to_csv(output_csv_path, index=False, encoding="utf-8-sig")
    output_report_path.write_text(
        json.dumps(artifacts.report, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def run_preprocessing_pipeline(raw_df: pd.DataFrame) -> dict[str, str]:
    """Run preprocessing and save the clean dataset inside the modular project."""
    ensure_project_dirs()
    artifacts = build_clean_dataset(raw_df)
    clean_csv_path = PROCESSED_DATA_DIR / "clean_reviews.csv"
    report_path = REPORTS_DIR / "phase2_preprocessing_report.json"
    save_preprocessing_outputs(artifacts, clean_csv_path, report_path)
    return {
        "clean_reviews_csv": str(clean_csv_path),
        "preprocessing_report": str(report_path),
    }
